.TH katriawm 1 "2015-12-25" "Katria Window Manager" "User Commands"
.\" --------------------------------------------------------------------
.SH NAME
katriawm \- Katria Window Manager
.\" --------------------------------------------------------------------
.SH SYNOPSIS
\fBkatriawm\fP
.\" --------------------------------------------------------------------
.SH DESCRIPTION
\fBkatriawm\fP is a simple window manager.
.P
\fBkatriawm\fP is usually controlled by \fBkatriac\fP(1). You should
have a look at that manpage.
.\" --------------------------------------------------------------------
.SH OPTIONS
There are no options to specify or files to read. Only the
$\fIDISPLAY\fP environment variable tells the program to which display
to connect to.
.\" --------------------------------------------------------------------
.SH ENVIRONMENT
.TP
.B DISPLAY
Target display.
.\" --------------------------------------------------------------------
.SH LICENSE
\fBkatriawm\fP is released as \(lqPIZZA-WARE\(rq. See the accompanying
\fILICENSE\fP file.
.\" --------------------------------------------------------------------
.SH HISTORY
\fBkatriawm\fP was originally written by Peter Hofmann. The project
was started in December 2015.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.BR katriac (1),
.BR sxhkd (1).
