.TH katriabi 1 "2016-01-06" "Katria Window Manager" "User Commands"
.\" --------------------------------------------------------------------
.SH NAME
katriabi \- Bar information for katriawm
.\" --------------------------------------------------------------------
.SH SYNOPSIS
\fBkatriabi\fP
.\" --------------------------------------------------------------------
.SH DESCRIPTION
\fBkatriawm\fP(1) creates a property on the root window. This property
contains some of \fBkatriawm\fP's internal state. It can be used to draw
a bar or \(lqpager\(rq.
.P
\fBkatriabi\fP can monitor said property and create output suitable for
display in a bar. Currently, \fBkatriabi\fP only supports
\fBlemonbar\fP(1).
.P
For each update of the property, \fBkatriabi\fP will print one line to
\fISTDOUT\fP.
.\" --------------------------------------------------------------------
.SH OPTIONS
There are no options to specify or files to read. Only the
$\fIDISPLAY\fP environment variable tells the program to which display
to connect to.
.\" --------------------------------------------------------------------
.SH ENVIRONMENT
.TP
.B DISPLAY
Target display.
.\" --------------------------------------------------------------------
.SH LICENSE
\fBkatriabi\fP is released as \(lqPIZZA-WARE\(rq. See the accompanying
\fILICENSE\fP file.
.\" --------------------------------------------------------------------
.SH HISTORY
\fBkatriabi\fP was originally written by Peter Hofmann. The project
was started in December 2015.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.BR katriawm (1),
.BR lemonbar (1).
